#!/bin/bash

# check there is a valid argument
if [[ $1 == "" ]]; then
  echo "You must specify a blueprint to apply"
  exit 1
fi

# Always install shipyard
curl -s https://shipyard.run/install | bash

# apply ths blueprint
shipyard run --force-update $1
