#!/bin/bash -e

echo "################################"
echo "Installing Shipyard to /usr/local/bin/shipyard"
echo ""
echo "Please note: You may be prompted for your password"
echo ""
echo "To remove Shipyard and all configuration use the command \"shipyard uninstall\""

# detect the OS version
os=$(uname)
binary="shipyard-darwin-amd64.zip"
version="v0.0.0.beta.11"
repo="https://github.com/shipyard-run/shipyard/releases/download/$version"

if [[ $os == "Linux" ]]; then
  binary="shipyard-linux-amd64.zip"
fi

echo "Downloading $repo/$binary"
curl -L -s -o /tmp/shipyard.zip "$repo/$binary"
cd /tmp
unzip shipyard.zip
rm shipyard.zip

CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
if [ ${CAN_I_RUN_SUDO} -gt 0 ]
then
  sudo mv shipyard /usr/local/bin
  sudo chmod +x /usr/local/bin/shipyard
else
  # try without sudo might be running in a container
  mv shipyard /usr/local/bin
  chmod +x /usr/local/bin/shipyard
fi


