#!/bin/bash -e

echo "################################"
echo "Installing Shipyard to /usr/local/bin/shipyard"
echo ""
echo "Please note: You may be prompted for your password"
echo ""
echo "To remove Shipyard and all configuration use the command \"shipyard uninstall\""

# detect the OS version
os=$(uname)
binary="shipyard-darwin-amd64.zip"
version="v0.0.0.alpha.11"
repo="https://github.com/shipyard-run/shipyard/releases/download/$version"

if [[ $os == "Linux" ]]; then
  binary="shipyard-linux-amd64.zip"
fi

echo "Downloading $repo/$binary"
curl -L -s -o /tmp/shipyard.zip "$repo/$binary"
cd /tmp
unzip shipyard.zip
sudo mv yard2 /usr/local/bin/shipyard
sudo chmod +x /usr/local/bin/shipyard
rm shipyard.zip
